<?php

namespace Database\Seeders;

use App\Models\Kabupaten;
use Illuminate\Database\Seeder;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Kabupaten::factory()->count(416)->sequence(
            //Provinsi Aceh
            ['name' => 'Aceh Barat'],
            ['name' => 'Aceh Barat Daya'],
            ['name' => 'Aceh Besar'],
            ['name' => 'Aceh Jaya'],
            ['name' => 'Aceh Selatan'],
            ['name' => 'Aceh Singkil'],
            ['name' => 'Aceh Tamiang'],
            ['name' => 'Aceh Tengah'],
            ['name' => 'Aceh Tenggara'],
            ['name' => 'Aceh Timur'],
            ['name' => 'Aceh Utara'],
            ['name' => 'Bener Meriah'],
            ['name' => 'Bireuen'],
            ['name' => 'Gayo Lues'],
            ['name' => 'Nagan Raya'],
            ['name' => 'Pidie'],
            ['name' => 'Pidie Jaya'],
            ['name' => 'Simeulue'],
            //Provinsi Sumatera Utara
            ['name' => 'Asahan'],
            ['name' => 'Batu Bara'],
            ['name' => 'Dairi'],
            ['name' => 'Deli Serdang'],
            ['name' => 'Humbang Hasundutan'],
            ['name' => 'Karo'],
            ['name' => 'Labuhanbatu'],
            ['name' => 'Labuhanbatu Selatan'],
            ['name' => 'Labuhanbatu Utara'],
            ['name' => 'Langkat'],
            ['name' => 'Mandailing Natal'],
            ['name' => 'Nias'],
            ['name' => 'Nias Barat'],
            ['name' => 'Nias Selatan'],
            ['name' => 'Nias Utara'],
            ['name' => 'Padang Lawas'],
            ['name' => 'Padang Lawas Utara'],
            ['name' => 'Pakpak Bharat'],
            ['name' => 'Samosir'],
            ['name' => 'Serdang Bedagai'],
            ['name' => 'Simalungun'],
            ['name' => 'Tapanuli Selatan'],
            ['name' => 'Tapanuli Tengah'],
            ['name' => 'Tapanuli Utara'],
            ['name' => 'Toba'],
            //Provinsi Sumatera Selatan
            ['name' => 'Banyuasin'],
            ['name' => 'Empat Lawang'],
            ['name' => 'Lahat'],
            ['name' => 'Muara Enim'],
            ['name' => 'Musi Banyuasin'],
            ['name' => 'Musi Rawas'],
            ['name' => 'Musi Rawas Utara'],
            ['name' => 'Ogan Ilir'],
            ['name' => 'Ogan Komering Ulu'],
            ['name' => 'Ogan Komering Ulu Timur'],
            ['name' => 'Penukal Abab Lematang Ilir'],
            //Provinsi Sumatera Barat
            ['name' => 'Agam'],
            ['name' => 'Dharmasraya'],
            ['name' => 'Kepulauan Mentawai'],
            ['name' => 'Lima Puluh Kota'],
            ['name' => 'Padang Pariaman'],
            ['name' => 'Pasaman'],
            ['name' => 'Pasaman Barat'],
            ['name' => 'Pesisir Selatan'],
            ['name' => 'Sijunjung'],
            ['name' => 'Solok'],
            ['name' => 'Solok Selatan'],
            ['name' => 'Tanah Datar'],
            //Provinsi Bengkulu
            ['name' => 'Bengkulu Selatan'],
            ['name' => 'Bengkulu Tengah'],
            ['name' => 'Bengkulu Utara'],
            ['name' => 'Kaur'],
            ['name' => 'Kepahiang'],
            ['name' => 'Lebong'],
            ['name' => 'Mukomuko'],
            ['name' => 'Rejang Lebong'],
            ['name' => 'Seluma'],
            //Provinsi Riau
            ['name' => 'Bengkalis'],
            ['name' => 'Indragiri Hilir'],
            ['name' => 'Indragiri Hulu'],
            ['name' => 'Kampar'],
            ['name' => 'Kepulauan Meranti'],
            ['name' => 'Kuantan Singingi'],
            ['name' => 'Pelalawan'],
            ['name' => 'Rokan Hilir'],
            ['name' => 'Rokan Hulu'],
            ['name' => 'Siak'],
            //Provinsi Kepulauan Riau
            ['name' => 'Bintan'],
            ['name' => 'Karimun'],
            ['name' => 'Kepulauan Anambas'],
            ['name' => 'Lingga'],
            ['name' => 'Natuna'],
            //Provinsi Jambi
            ['name' => 'Batanghari'],
            ['name' => 'Bungo'],
            ['name' => 'Kerinci'],
            ['name' => 'Merangin'],
            ['name' => 'Muaro Jambi'],
            ['name' => 'Sarolangun'],
            ['name' => 'Tanjung Jabung Barat'],
            ['name' => 'Tanjung Jabung Timur'],
            ['name' => 'Tebo'],
            //Provinsi Lampung
            ['name' => 'Lampung Barat'],
            ['name' => 'Lampung Selatan'],
            ['name' => 'Lampung Tengah'],
            ['name' => 'Lampung Timur'],
            ['name' => 'Lampung Utara'],
            ['name' => 'Mesuji'],
            ['name' => 'Pesawaran'],
            ['name' => 'Pesisir Barat'],
            ['name' => 'Pringsewu'],
            ['name' => 'Tanggamus'],
            ['name' => 'Tulang Bawang'],
            ['name' => 'Tulang Bawang Barat'],
            ['name' => 'Way Kanan'],
            //Provinsi Bangka Belitung
            ['name' => 'Bangka'],
            ['name' => 'Bangka Barat'],
            ['name' => 'Bangka Selatan'],
            ['name' => 'Bangka Tengah'],
            ['name' => 'Belitung'],
            ['name' => 'Belitung Timur'],
            //Provinsi Kalimantan Barat
            ['name' => 'Bengkayang'],
            ['name' => 'Kapuas Hulu'],
            ['name' => 'Kayong Utara'],
            ['name' => 'Ketapang'],
            ['name' => 'Kubu Raya'],
            ['name' => 'Landak'],
            ['name' => 'Melawi'],
            ['name' => 'Mempawah'],
            ['name' => 'Sambas'],
            ['name' => 'Sanggau'],
            ['name' => 'Sekadau'],
            ['name' => 'Sintang'],
            //Provinsi Kalimantan Timur
            ['name' => 'Berau'],
            ['name' => 'Kutai Barat'],
            ['name' => 'Kutai Kartanegara'],
            ['name' => 'Kutai Timur'],
            ['name' => 'Mahakam Ulu'],
            ['name' => 'Paser'],
            ['name' => 'Penajam Paser Utara'],
            //Provinsi Kalimantan Selatan
            ['name' => 'Balangan'],
            ['name' => 'Banjar'],
            ['name' => 'Barito Kuala'],
            ['name' => 'Hulu Sungai Selatan'],
            ['name' => 'Hulu Sungai Tengah'],
            ['name' => 'Hulu Sungai Utara'],
            ['name' => 'Kotabaru'],
            ['name' => 'Tabalong'],
            ['name' => 'Tanah Bumbu'],
            ['name' => 'Tanah Laut'],
            ['name' => 'Tapin'],
            //Provinsi Kalimantan Tengah
            ['name' => 'Barito Selatan'],
            ['name' => 'Barito Timur'],
            ['name' => 'Barito Utara'],
            ['name' => 'Gunung Mas'],
            ['name' => 'Kapuas'],
            ['name' => 'Katingan'],
            ['name' => 'Kotawaringin Barat'],
            ['name' => 'Kotawaringin Timur'],
            ['name' => 'Lamandau'],
            ['name' => 'Murung Raya'],
            ['name' => 'Pulang Pisau'],
            ['name' => 'Seruyan'],
            ['name' => 'Sukamara'],
            //Provinsi Kalimantan Utara
            ['name' => 'Bulungan'],
            ['name' => 'Malinau'],
            ['name' => 'Nunukan'],
            ['name' => 'Tana Tidung'],
            //Provinsi Banten
            ['name' => 'Lebak'],
            ['name' => 'Pandeglang'],
            ['name' => 'Serang'],
            ['name' => 'Tangerang'],
            //Provinsi DKI Jakarta
            ['name' => 'Administrasi Kepulauan Seribu'],
            //Provinsi Jawa Barat
            ['name' => 'Bandung'],
            ['name' => 'Bandung Barat'],
            ['name' => 'Bekasi'],
            ['name' => 'Bogor'],
            ['name' => 'Ciamis'],
            ['name' => 'Cianjur'],
            ['name' => 'Cirebon'],
            ['name' => 'Garut'],
            ['name' => 'Indramayu'],
            ['name' => 'Karawang'],
            ['name' => 'Kuningan'],
            ['name' => 'Majalengka'],
            ['name' => 'Pangandaran'],
            ['name' => 'Purwakarta'],
            ['name' => 'Subang'],
            ['name' => 'Sukabumi'],
            ['name' => 'Sumedang'],
            ['name' => 'Tasikmalaya'],
            //Provinsi Jawa Tengah
            ['name' => 'Banjarnegara'],
            ['name' => 'Banyumas'],
            ['name' => 'Batang'],
            ['name' => 'Blora'],
            ['name' => 'Boyolali'],
            ['name' => 'Brebes'],
            ['name' => 'Cilacap'],
            ['name' => 'Demak'],
            ['name' => 'Grobogan'],
            ['name' => 'Jepara'],
            ['name' => 'Karanganyar'],
            ['name' => 'Kebumen'],
            ['name' => 'Kendal'],
            ['name' => 'Klaten'],
            ['name' => 'Kudus'],
            ['name' => 'Magelang'],
            ['name' => 'Pati'],
            ['name' => 'Pekalongan'],
            ['name' => 'Pemalang'],
            ['name' => 'Purbalingga'],
            ['name' => 'Purworejo'],
            ['name' => 'Rembang'],
            ['name' => 'Semarang'],
            ['name' => 'Sragen'],
            ['name' => 'Sukoharjo'],
            ['name' => 'Tegal'],
            ['name' => 'Temanggung'],
            ['name' => 'Wonogiri'],
            ['name' => 'Wonosobo'],
            //Provinsi Daerah Istimewa Yogyakarta
            ['name' => 'Bantul'],
            ['name' => 'Gunung Kidul'],
            ['name' => 'Kulon Progo'],
            ['name' => 'Sleman'],
            //Provinsi Jawa Timur
            ['name' => 'Bangkalan'],
            ['name' => 'Banyuwangi'],
            ['name' => 'Blitar'],
            ['name' => 'Bojonegoro'],
            ['name' => 'Bondowoso'],
            ['name' => 'Gresik'],
            ['name' => 'Jember'],
            ['name' => 'Jombang'],
            ['name' => 'Kediri'],
            ['name' => 'Lamongan'],
            ['name' => 'Lumajang'],
            ['name' => 'Madiun'],
            ['name' => 'Magetan'],
            ['name' => 'Malang'],
            ['name' => 'Mojokerto'],
            ['name' => 'Nganjuk'],
            ['name' => 'Ngawi'],
            ['name' => 'Pacitan'],
            ['name' => 'Pamekasan'],
            ['name' => 'Pasuruan'],
            ['name' => 'Ponorogo'],
            ['name' => 'Probolinggo'],
            ['name' => 'Sampang'],
            ['name' => 'Sidoarjo'],
            ['name' => 'Situbondo'],
            ['name' => 'Sumenep'],
            ['name' => 'Trenggalek'],
            ['name' => 'Tuban'],
            ['name' => 'Tulungagung'],
            //Provinsi Bali
            ['name' => 'Badung'],
            ['name' => 'Bangli'],
            ['name' => 'Buleleng'],
            ['name' => 'Gianyar'],
            ['name' => 'Jembrana'],
            ['name' => 'Karangasem'],
            ['name' => 'Klungkung'],
            ['name' => 'Tabanan'],
            //Provinsi Nusa Tenggara Timur
            ['name' => 'Alor'],
            ['name' => 'Belu'],
            ['name' => 'Ende'],
            ['name' => 'Flores Timur'],
            ['name' => 'Kupang'],
            ['name' => 'Lembata'],
            ['name' => 'Malaka'],
            ['name' => 'Manggarai'],
            ['name' => 'Manggarai Barat'],
            ['name' => 'Manggarai Timur'],
            ['name' => 'Nagekeo'],
            ['name' => 'Ngada'],
            ['name' => 'Rote Ndao'],
            ['name' => 'Sabu Raijua'],
            ['name' => 'Sikka'],
            ['name' => 'Sumba Barat'],
            ['name' => 'Sumba Barat Daya'],
            ['name' => 'Sumba Tengah'],
            ['name' => 'Sumba Timur'],
            ['name' => 'Timor Tengah Selatan'],
            ['name' => 'Timor Tengah Utara'],
            //Provinsi Nusa Tenggara Barat
            ['name' => 'Bima'],
            ['name' => 'Dompu'],
            ['name' => 'Lombok Barat'],
            ['name' => 'Lombok Tengah'],
            ['name' => 'Lombok Timur'],
            ['name' => 'Lombok Utara'],
            ['name' => 'Sumbawa'],
            ['name' => 'Sumbawa Barat'],
            //Provinsi Gorontalo
            ['name' => 'Boalemo'],
            ['name' => 'Bone Bolango'],
            ['name' => 'Gorontalo'],
            ['name' => 'Gorontalo Utara'],
            ['name' => 'Pohuwato'],
            //Provinsi Sulawesi Barat
            ['name' => 'Majene'],
            ['name' => 'Mamasa'],
            ['name' => 'Mamuju'],
            ['name' => 'Mamuju Tengah'],
            ['name' => 'Pasangkayu'],
            ['name' => 'Polewali Mandar'],
            //Provinsi Sulawesi Tengah
            ['name' => 'Poso'],
            ['name' => 'Banggai'],
            ['name' => 'Banggai Kepulauan'],
            ['name' => 'Banggai Laut'],
            ['name' => 'Buol'],
            ['name' => 'Donggala'],
            ['name' => 'Morowali'],
            ['name' => 'Morowali Utara'],
            ['name' => 'Parigi Moutong'],
            ['name' => 'Sigi'],
            ['name' => 'Tojo Una Una'],
            ['name' => 'Tolitoli'],
            //Provinsi Sulawesi Utara
            ['name' => 'Bolaang Mongondow'],
            ['name' => 'Bolaang Mongondow Selatan'],
            ['name' => 'Bolaang Mongondow Timur'],
            ['name' => 'Bolaang Mongondow Utara'],
            ['name' => 'Kepulauan Sangihe'],
            ['name' => 'Kepulauan Siau Tagulandang Biaro'],
            ['name' => 'Kepulauan Talaud'],
            ['name' => 'Minahasa'],
            ['name' => 'Minahasa Selatan'],
            ['name' => 'Minahasa Tenggara'],
            ['name' => 'Minahasa Utara'],
            //Provinsi Sulawesi Tenggara
            ['name' => 'Bombana'],
            ['name' => 'Buton'],
            ['name' => 'Buton Selatan'],
            ['name' => 'Buton Tengah'],
            ['name' => 'Buton Utara'],
            ['name' => 'Kolaka'],
            ['name' => 'Kolaka Timur'],
            ['name' => 'Kolaka Utara'],
            ['name' => 'Konawe'],
            ['name' => 'Konawe Kepulauan'],
            ['name' => 'Konawe Selatan'],
            ['name' => 'Konawe Utara'],
            ['name' => 'Muna'],
            ['name' => 'Muna Barat'],
            ['name' => 'Wakatobi'],
            //Provinsi Sulawesi Selatan
            ['name' => 'Bantaeng'],
            ['name' => 'Barru'],
            ['name' => 'Bone'],
            ['name' => 'Bulukumba'],
            ['name' => 'Enrekang'],
            ['name' => 'Gowa'],
            ['name' => 'Jenepento'],
            ['name' => 'Kepulauan Selayar'],
            ['name' => 'Luwu'],
            ['name' => 'Luwu Timur'],
            ['name' => 'Luwu Utara'],
            ['name' => 'Maros'],
            ['name' => 'Pangkajene dan Kepulauan'],
            ['name' => 'Pinrang'],
            ['name' => 'Sidenreng Rappang'],
            ['name' => 'Sinjai'],
            ['name' => 'Soppeng'],
            ['name' => 'Takalar'],
            ['name' => 'Tana Toraja'],
            ['name' => 'Toraja Utara'],
            ['name' => 'Wajo'],
            //Provinsi Maluku Utara
            ['name' => 'Halmahera Barat'],
            ['name' => 'Halmahera Selatan'],
            ['name' => 'Halmahera Tengah'],
            ['name' => 'Halmahera Timur'],
            ['name' => 'Halmahera Utara'],
            ['name' => 'Kepulauan Sula'],
            ['name' => 'Pulau Morotai'],
            ['name' => 'Pulau Taliabu'],
            //Provinsi Maluku
            ['name' => 'Buru'],
            ['name' => 'Buru Selatan'],
            ['name' => 'Kepulauan Aru'],
            ['name' => 'Kepulauan Tanimbar'],
            ['name' => 'Maluku Barat Daya'],
            ['name' => 'Maluku Tengah'],
            ['name' => 'Maluku Tenggara'],
            ['name' => 'Seram Bagian Barat'],
            ['name' => 'Seram Bagian Timur'],
            //Provinsi Papua Barat
            ['name' => 'Fakfak'],
            ['name' => 'Kaimana'],
            ['name' => 'Manokwari'],
            ['name' => 'Manokwari Selatan'],
            ['name' => 'Pegunungan Arfak'],
            ['name' => 'Teluk Bintuni'],
            ['name' => 'Teluk Wondama'],
            //Provinsi Papua
            ['name' => 'Biak Numfor'],
            ['name' => 'Jayapura'],
            ['name' => 'Keerom'],
            ['name' => 'Kepulauan Yapen'],
            ['name' => 'Mamberamo Raya'],
            ['name' => 'Sarmi'],
            ['name' => 'Supiori'],
            ['name' => 'Waropen'],
            //Provinsi Papua Tengah
            ['name' => 'Deiyai'],
            ['name' => 'Dogiyai'],
            ['name' => 'Intan Jaya'],
            ['name' => 'Mimika'],
            ['name' => 'Nabire'],
            ['name' => 'Paniai'],
            ['name' => 'Puncak'],
            ['name' => 'Puncak Jaya'],
            //Provinsi Papua Pegunungan
            ['name' => 'Jayawijaya'],
            ['name' => 'Lanny Jaya'],
            ['name' => 'Mamberamo Tengah'],
            ['name' => 'Nduga'],
            ['name' => 'Pegunungan Bintang'],
            ['name' => 'Tolikara'],
            ['name' => 'Yahukimo'],
            ['name' => 'Yalimo'],
            //Provinsi Papua Selatan
            ['name' => 'Asmat'],
            ['name' => 'Boven Digoel'],
            ['name' => 'Mappi'],
            ['name' => 'Merauke'],
            //Provinsi Papua Barat Daya
            ['name' => 'Maybrat'],
            ['name' => 'Raja Ampat'],
            ['name' => 'Sorong'],
            ['name' => 'Sorong Selatan'],
            ['name' => 'Tambrauw']
        )->create();
    }
}
